<?php
/**
 * @file
 * Drupal integration with jQuery ViewportChecker library
 */

/**
 * Implements hook_init().
 */
function viewportchecker_init() {
  drupal_load('module', 'libraries');
  
  if (variable_get('viewportchecker_devel', FALSE) == TRUE) {
    libraries_load('jquery.viewportchecker');
  }
  else {
    libraries_load('jquery.viewportchecker', 'minified');
  }
}

/**
 * Implements hook_libraries_info().
 */
function viewportchecker_libraries_info() {
  $libraries['jquery.viewportchecker'] = array(
    'name' => 'Jquery ViewportChecker',
    'vendor url' => 'https://github.com/dirkgroenen/jQuery-viewport-checker',
    'download url' => 'https://github.com/dirkgroenen/jQuery-viewport-checker/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/((?:\d+\.?){2,3})/',
    ),
    'files' => array(
      'js' => array('jquery.viewportchecker.js'),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array('jquery.viewportchecker.min.js'),
        ),
        'variant arguments' => array(
          'variant' => 'minified',
        ),
      ),
    ),
  );
  return $libraries;
}

/**
 * Form for ViewportChecker library settings.
 */
function viewportchecker_settings_form() {
  $form = array();

  $form['library'] = array(
    '#type' => 'fieldset',
    '#title' => 'Library',
    '#description' => t("Unless you are helping to develop the viewportchecker module, all these are not needed to use viewportchecker."),
  );

  $form['library']['viewportchecker_devel'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use uncompressed CSS'),
    '#description' => t('Load the uncompressed version of viewportchecker. This SHOULD NOT be checked on production sites.'),
    '#default_value' => variable_get('viewportchecker_devel', FALSE),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_menu().
 */
function viewportchecker_menu() {
  $items['admin/config/media/viewportchecker'] = array(
    'title' => 'jQuery ViewportChecker',
    'description' => 'Configure jQuery ViewportChecker.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('viewportchecker_settings_form'),
    'access arguments' => array('administer viewportchecker'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function viewportchecker_permission() {
  return array(
    'administer viewportchecker' => array(
      'title' => t('Administer the viewportchecker library'),
    ),
  );
}